// <auto-generated />
using ListadoAutos.API.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListadoAutos.API.Migrations
{
    [DbContext(typeof(ListadoAutosDbContext))]
    [Migration("20230201014538_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ListadoAutos.API.Modelos.Auto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Autos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marca = "Honda",
                            Modelo = "Civic",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            Id = 2,
                            Marca = "Toyota",
                            Modelo = "Prado",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            Id = 3,
                            Marca = "Audi",
                            Modelo = "A5",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            Id = 4,
                            Marca = "Chevrolet",
                            Modelo = "Spark",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            Id = 5,
                            Marca = "BMW",
                            Modelo = "M3",
                            Placa = "ABC1234"
                        },
                        new
                        {
                            Id = 6,
                            Marca = "Nissan",
                            Modelo = "Note",
                            Placa = "ABC1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
